=== xjrga/schemas/blood_pressure_data_point_set.xsd
<xsd:schema version="1.0"
	    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="blood_pressure_data_point_set">
	<xsd:annotation>
	    <xsd:documentation>
		Data Exchange Document Schema For Blood Pressure Measurement Data Point	Set
		Author: Jorge Garcia R de Alba
	    </xsd:documentation>
	</xsd:annotation>
	<xsd:complexType>
	    <xsd:sequence>
		<xsd:element name="id" type="xsd:string" minOccurs="1" maxOccurs="1"/>
		<xsd:element name="blood_pressure_data_point" type="blood_pressure_data_point_type" minOccurs="1" maxOccurs="unbounded"/>
	    </xsd:sequence>
	</xsd:complexType>
	<xsd:unique name="Uniquely_Specified_Blood_Pressure_Measurement_Data_Point">
	    <xsd:selector xpath="blood_pressure_data_point"/>
	    <xsd:field xpath="timestamp"/>	    
	</xsd:unique>
    </xsd:element>
    <!-- Blood Pressure Measurement Data Point -->
    <xsd:complexType name="blood_pressure_data_point_type">
	<xsd:sequence>            
	    <xsd:element name="sys" type="systolic_pressure_type" minOccurs="1" maxOccurs="1"/>
	    <xsd:element name="dia" type="diastolic_pressure_type" minOccurs="1" maxOccurs="1"/>
	    <xsd:element name="pulse" type="pulse_type" minOccurs="1" maxOccurs="1"/>
	    <xsd:element name="timestamp" type="dateTime_type" minOccurs="1" maxOccurs="1"/>
	</xsd:sequence>
    </xsd:complexType>
    <!-- Sys (mmHg) -->
    <xsd:simpleType name="systolic_pressure_type">	
	<xsd:restriction base="xsd:nonNegativeInteger">
	    <xsd:minInclusive value="0"/>
	    <xsd:maxInclusive value="400"/>
	</xsd:restriction>
    </xsd:simpleType>
    <!-- Dia (mmHg) -->
    <xsd:simpleType name="diastolic_pressure_type">
	<xsd:restriction base="xsd:nonNegativeInteger">
	    <xsd:minInclusive value="0"/>
	    <xsd:maxInclusive value="400"/>
	</xsd:restriction>
    </xsd:simpleType>
    <!-- Pulse (beats/min) -->
    <xsd:simpleType name="pulse_type">
	<xsd:restriction base="xsd:nonNegativeInteger">
	    <xsd:minInclusive value="0"/>
	    <xsd:maxInclusive value="400"/>
	</xsd:restriction>
    </xsd:simpleType>
    <!-- Date Time -->
    <xsd:simpleType name="dateTime_type">
	<xsd:restriction base="xsd:dateTime">
	</xsd:restriction>
    </xsd:simpleType>    
</xsd:schema>

=== xjrga/schemas/blood_pressure_data_point_set.xml
<?xml version="1.0" encoding="UTF-8"?>
<blood_pressure_data_point_set
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='blood_pressure_data_point_set.xsd'>
    <id>abc</id>
    <blood_pressure_data_point>
	<sys>120</sys>
	<dia>80</dia>
	<pulse>45</pulse>
	<timestamp>2021-04-20T08:00:00</timestamp>
    </blood_pressure_data_point>
    <blood_pressure_data_point>
	<sys>120</sys>
	<dia>80</dia>
	<pulse>45</pulse>
	<timestamp>2021-04-20T08:03:00</timestamp>
    </blood_pressure_data_point>       
</blood_pressure_data_point_set>
